"""Shared immutable model provenance; no model formulas or automatic registrations."""
from datetime import datetime, timezone
from enum import Enum
import hashlib
import json
import os
import re
import subprocess
from pathlib import Path

from . import config


class ModelType(str, Enum):
    CLUB = 'club'
    PLAYER = 'player'
    LINEUP = 'lineup'
    MATCH = 'match'
    BETTING = 'betting'
    FANTASY = 'fantasy'


def _timestamp(value):
    if value is None:
        return None
    if not isinstance(value, datetime) or value.tzinfo is None or value.utcoffset() is None:
        raise ValueError('Timestamps must be timezone-aware datetime values')
    return value.astimezone(timezone.utc).isoformat()


def snapshot_times(*, captured_at, effective_at):
    """UTC observation/event timestamps; created_at must be generated by the DB.

    captured_at may follow effective_at for explicitly labelled reconstructions.
    This helper does not imply that a reconstructed snapshot was available live.
    """
    if captured_at is None or effective_at is None:
        raise ValueError('Snapshot observation and event timestamps are required')
    return {'captured_at': _timestamp(captured_at), 'effective_at': _timestamp(effective_at)}


def current_code_sha():
    """Return available commit identity; never claim the commit covers dirty edits."""
    root = Path(__file__).resolve().parent.parent
    try:
        dirty = subprocess.check_output(['git', 'status', '--porcelain', '--untracked-files=normal'],
                                        cwd=root, stderr=subprocess.DEVNULL, timeout=2, text=True)
        if dirty.strip():
            return None
        sha = subprocess.check_output(['git', 'rev-parse', 'HEAD'], cwd=root,
                                      stderr=subprocess.DEVNULL, timeout=2, text=True).strip()
    except (OSError, subprocess.SubprocessError):
        sha = os.getenv('GITHUB_SHA')
    return sha if sha and re.fullmatch(r'[0-9a-f]{40}(?:[0-9a-f]{24})?', sha) else None


def _validate_json(value):
    """Require explicit JSON configuration; never collect env vars or module globals."""
    if isinstance(value, dict):
        for key, item in value.items():
            if not isinstance(key, str):
                raise ValueError('Configuration keys must be strings')
            normalized = re.sub(r'[^a-z0-9]', '', key.lower())
            if any(word in normalized for word in ('password', 'secret', 'token', 'apikey', 'databaseurl')):
                raise ValueError('Credentials do not belong in model configuration')
            _validate_json(item)
    elif isinstance(value, list):
        for item in value:
            _validate_json(item)
    elif value is not None and not isinstance(value, (str, int, float, bool)):
        raise ValueError('Configuration must contain JSON values only')


def version_metadata(model_type, version_name, *, configuration=None, code_sha=None,
                     training_window=None, evaluation_window=None, notes=''):
    """Build deterministic metadata/ID without IO; absent SHA stays explicitly unknown.

    Window pairs are half-open [start, end). Notes participate in immutable identity.
    Numeric JSON types are significant (1 and 1.0 produce different identities).
    """
    model_type = ModelType(model_type).value
    if not isinstance(version_name, str) or not version_name.strip():
        raise ValueError('A non-empty version name is required')
    if not isinstance(notes, str):
        raise ValueError('Notes must be text')
    if code_sha is not None and (not isinstance(code_sha, str) or not re.fullmatch(r'[0-9a-f]{40}(?:[0-9a-f]{24})?', code_sha)):
        raise ValueError('code_sha must be a full lowercase Git SHA or None')
    configuration = {} if configuration is None else configuration
    if not isinstance(configuration, dict):
        raise ValueError('Configuration must be a JSON object')
    _validate_json(configuration)
    metadata = dict(model_type=model_type, version_name=version_name.strip(),
                    code_sha=code_sha, configuration=configuration, notes=notes)
    for name, window in [('training', training_window), ('evaluation', evaluation_window)]:
        if window is None:
            start = end = None
        else:
            if len(window) != 2:
                raise ValueError('Windows require start and end')
            start, end = map(_timestamp, window)
            if start is None or end is None or start >= end:
                raise ValueError('Window start must precede end')
        metadata[name + '_start'] = start
        metadata[name + '_end'] = end
    serialized = json.dumps(metadata, sort_keys=True, separators=(',', ':'), allow_nan=False)
    # Round-trip isolates the metadata from subsequent mutation of caller dictionaries.
    metadata = json.loads(serialized)
    metadata['model_version_id'] = 'mv_' + hashlib.sha256(serialized.encode()).hexdigest()
    return metadata


def register_model_version(conn, model_type, version_name, **kwargs):
    """Insert or reuse provenance in the caller's transaction; never commits.

    Pass current_code_sha() explicitly if automatic commit discovery is desired.
    Reuse the returned ID throughout a run instead of scattering version strings.
    """
    config.require_db_write('register model version')
    metadata = version_metadata(model_type, version_name, **kwargs)
    params = {**metadata, 'configuration': json.dumps(metadata['configuration'], allow_nan=False)}
    conn.execute('''INSERT INTO model_versions
        (model_version_id,model_type,version_name,code_sha,configuration,
         training_start,training_end,evaluation_start,evaluation_end,notes)
        VALUES (%(model_version_id)s,%(model_type)s,%(version_name)s,%(code_sha)s,
                %(configuration)s::jsonb,%(training_start)s,%(training_end)s,
                %(evaluation_start)s,%(evaluation_end)s,%(notes)s)
        ON CONFLICT (model_version_id) DO NOTHING''', params)
    return metadata['model_version_id']
